package model

import (
	"time"

	"gorm.io/gorm"
)

// PRReviewTask represents a code review job in the database.
type PRReviewTask struct {
	ID         uint           `gorm:"primaryKey;autoIncrement" json:"id"`
	GitHubURL  string         `gorm:"type:varchar(512);not null;index" json:"github_url"`
	RepoOwner  string         `gorm:"type:varchar(128);not null" json:"repo_owner"`
	RepoName   string         `gorm:"type:varchar(128);not null" json:"repo_name"`
	PRNumber   int            `gorm:"type:int;not null" json:"pr_number"`
	Status     string         `gorm:"type:varchar(32);default:'pending';not null" json:"status"` // pending | processing | success | failed
	Summary    string         `gorm:"type:text" json:"summary"`                                  // JSON encoded summary payload
	RawDiff    string         `gorm:"type:longtext" json:"raw_diff"`                             // The fetched git diff text
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`
	
	// Has-Many association for the detailed cards
	Comments   []ReviewComment `gorm:"foreignKey:TaskID;constraint:OnDelete:CASCADE" json:"comments,omitempty"`
}

// ReviewComment represents a single inline review block/card generated by AI.
type ReviewComment struct {
	ID            uint           `gorm:"primaryKey;autoIncrement" json:"id"`
	TaskID        uint           `gorm:"not null;index" json:"task_id"`
	FilePath      string         `gorm:"type:varchar(512);not null" json:"file_path"`
	LineNumber    int            `gorm:"type:int;not null" json:"line_number"`
	Severity      string         `gorm:"type:varchar(32);not null" json:"severity"` // CRITICAL | WARNING | SUGGESTION
	Reason        string         `gorm:"type:text;not null" json:"reason"`
	SuggestedCode string         `gorm:"type:text" json:"suggested_code"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
}
